opt_in_rules: 
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - explicit_self
  - file_header
  - indentation_width
  - literal_expression_end_indentation
  - multiline_function_chains
